import React, { Component } from 'react';
import ImageGallery from "react-image-gallery";
import "react-image-gallery/styles/css/image-gallery.css";
import "../css/AvatarGallery.css"

function importAll(r) {
    return r.keys().map(r);
}

const images = ["/assets/default-avis/neurondark.png",
"/assets/roles/roleimg_EM-00-00-insanecop.png",
"/assets/roles/roleimg_EM-00-00-villager.png",
"/assets/roles/roleimg_EM-00-01-cop-paranoid.png",
"/assets/roles/roleimg_EM-00-01-journalist.png",
"/assets/roles/roleimg_EM-00-02-miller.png",
"/assets/roles/roleimg_EM-00-02-pathologist.png",
"/assets/roles/roleimg_EM-00-03-invisibleman.png",
"/assets/roles/roleimg_EM-00-03-leader.png",
"/assets/roles/roleimg_EM-00-04-telepath.png",
"/assets/roles/roleimg_EM-00-05-chef.png",
"/assets/roles/roleimg_EM-00-06-judge.png",
"/assets/roles/roleimg_EM-00-07-lk.png",
"/assets/roles/roleimg_EM-00-08-cthulhu.png",
"/assets/roles/roleimg_EM-00-09-mistletoe.png",
"/assets/roles/roleimg_EM-00-10-oldmaid.png",
"/assets/roles/roleimg_EM-00-11-consigliere.png",
"/assets/roles/roleimg_EM-00-12-janitor.png",
"/assets/roles/roleimg_EM-00-13-poisoner.png",
"/assets/roles/roleimg_EM-00-14-paralyzer.png",
"/assets/roles/roleimg_EM-00-15-terrorist.png",
"/assets/roles/roleimg_EM-00-16-don.png",
"/assets/roles/roleimg_EM-00-17-bride.png",
"/assets/roles/roleimg_EM-00-18-cyborg.png",
"/assets/roles/roleimg_EM-00-19-forager.png",
"/assets/roles/roleimg_EM-00-20-king.png",
"/assets/roles/roleimg_EM-00-21-snowqueen.png",
"/assets/roles/roleimg_EM-00-22-partycrasher.png",
"/assets/roles/roleimg_EM-00-23-troublemaker.png",
"/assets/roles/roleimg_EM-00-24-polarbear.png",
"/assets/roles/roleimg_EM-01-00-cop-confused.png",
"/assets/roles/roleimg_EM-01-00-vanilla.png",
"/assets/roles/roleimg_EM-01-01-cop.png",
"/assets/roles/roleimg_EM-01-01-mortician.png",
"/assets/roles/roleimg_EM-01-02-suspect.png",
"/assets/roles/roleimg_EM-01-02-vigilante.png",
"/assets/roles/roleimg_EM-01-03-bulletproof.png",
"/assets/roles/roleimg_EM-01-04-agent.png",
"/assets/roles/roleimg_EM-01-05-turncoat.png",
"/assets/roles/roleimg_EM-01-06-gallis.png",
"/assets/roles/roleimg_EM-01-07-keymaker.png",
"/assets/roles/roleimg_EM-01-08-zombie.png",
"/assets/roles/roleimg_EM-01-09-prophet.png",
"/assets/roles/roleimg_EM-01-10-autocrat.png",
"/assets/roles/roleimg_EM-01-11-don.png",
"/assets/roles/roleimg_EM-01-12-interrogator.png",
"/assets/roles/roleimg_EM-01-13-driver.png",
"/assets/roles/roleimg_EM-01-14-paparazzi.png",
"/assets/roles/roleimg_EM-01-15-mastermind.png",
"/assets/roles/roleimg_EM-01-16-sidekick.png",
"/assets/roles/roleimg_EM-01-17-trickster.png",
"/assets/roles/roleimg_EM-01-18-president.png",
"/assets/roles/roleimg_EM-01-19-gossiper.png",
"/assets/roles/roleimg_EM-01-20-phantom.png",
"/assets/roles/roleimg_EM-01-21-cyclist.png",
"/assets/roles/roleimg_EM-01-22-turkey.png",
"/assets/roles/roleimg_EM-01-23-necromancer.png",
"/assets/roles/roleimg_EM-01-24-gingerbreadman.png",
"/assets/roles/roleimg_EM-02-00-doctor.png",
"/assets/roles/roleimg_EM-02-01-cop-lazy.png",
"/assets/roles/roleimg_EM-02-02-sheriff.png",
"/assets/roles/roleimg_EM-02-03-bleeder.png",
"/assets/roles/roleimg_EM-02-04-celeb.png",
"/assets/roles/roleimg_EM-02-05-enchantress.png",
"/assets/roles/roleimg_EM-02-06-tree.png",
"/assets/roles/roleimg_EM-02-07-gunsmith.png",
"/assets/roles/roleimg_EM-02-08-fool.png",
"/assets/roles/roleimg_EM-02-09-alien.png",
"/assets/roles/roleimg_EM-02-10-politician.png",
"/assets/roles/roleimg_EM-02-11-framer.png",
"/assets/roles/roleimg_EM-02-12-whisperer.png",
"/assets/roles/roleimg_EM-02-13-gramps.png",
"/assets/roles/roleimg_EM-02-14-scout.png",
"/assets/roles/roleimg_EM-02-15-wtfisthis.png",
"/assets/roles/roleimg_EM-02-16-huntsman.png",
"/assets/roles/roleimg_EM-02-17-diabolist.png",
"/assets/roles/roleimg_EM-02-18-nomad.png",
"/assets/roles/roleimg_EM-02-19-jacktheripper.png",
"/assets/roles/roleimg_EM-02-20-usurper.png",
"/assets/roles/roleimg_EM-02-21-demolitionist.png",
"/assets/roles/roleimg_EM-02-22-medium.png",
"/assets/roles/roleimg_EM-02-23-mummy.png",
"/assets/roles/roleimg_EM-02-24-cultleader.png",
"/assets/roles/roleimg_EM-03-00-nurse.png",
"/assets/roles/roleimg_EM-03-01-watcher.png",
"/assets/roles/roleimg_EM-03-02-dep.png",
"/assets/roles/roleimg_EM-03-03-bomb.png",
"/assets/roles/roleimg_EM-03-04-loudmouth.png",
"/assets/roles/roleimg_EM-03-05-priest.png",
"/assets/roles/roleimg_EM-03-06-secretary.png",
"/assets/roles/roleimg_EM-03-07-mimic.png",
"/assets/roles/roleimg_EM-03-08-lover.png",
"/assets/roles/roleimg_EM-03-09-werewolf.png",
"/assets/roles/roleimg_EM-03-10-silencer.png",
"/assets/roles/roleimg_EM-03-11-hooker.png",
"/assets/roles/roleimg_EM-03-12-spy.png",
"/assets/roles/roleimg_EM-03-13-fuckireallydontknow.png",
"/assets/roles/roleimg_EM-03-14-associate.png",
"/assets/roles/roleimg_EM-03-15-unknown.png",
"/assets/roles/roleimg_EM-03-16-prosecutor.png",
"/assets/roles/roleimg_EM-03-17-gambler.png",
"/assets/roles/roleimg_EM-03-18-librarian.png",
"/assets/roles/roleimg_EM-03-19-robinhood.png",
"/assets/roles/roleimg_EM-03-20-jailkeeper.png",
"/assets/roles/roleimg_EM-03-21-butler.png",
"/assets/roles/roleimg_EM-03-22-neighbour.png",
"/assets/roles/roleimg_EM-03-23-ghost.png",
"/assets/roles/roleimg_EM-03-24-charmer.png",
"/assets/roles/roleimg_EM-04-00-surgeon.png",
"/assets/roles/roleimg_EM-04-01-tracker.png",
"/assets/roles/roleimg_EM-04-02-drunk.png",
"/assets/roles/roleimg_EM-04-03-granny.png",
"/assets/roles/roleimg_EM-04-04-mason.png",
"/assets/roles/roleimg_EM-04-05-trapper.png",
"/assets/roles/roleimg_EM-04-06-virgin.png",
"/assets/roles/roleimg_EM-04-07-santa.png",
"/assets/roles/roleimg_EM-04-08-lyncher.png",
"/assets/roles/roleimg_EM-04-09-amnesiac.png",
"/assets/roles/roleimg_EM-04-10-blinder.png",
"/assets/roles/roleimg_EM-04-11-disguiser.png",
"/assets/roles/roleimg_EM-04-12-lawyer.png",
"/assets/roles/roleimg_EM-04-13-fiddler.png",
"/assets/roles/roleimg_EM-04-14-fabricator.png",
"/assets/roles/roleimg_EM-04-15-seer.png",
"/assets/roles/roleimg_EM-04-16-snowman.png",
"/assets/roles/roleimg_EM-04-17-apprentice.png",
"/assets/roles/roleimg_EM-04-18-plumber.png",
"/assets/roles/roleimg_EM-04-19-seer2.png",
"/assets/roles/roleimg_EM-04-20-recruit.png",
"/assets/roles/roleimg_EM-04-21-housekeeper.png",
"/assets/roles/roleimg_EM-04-22-crank-exceptfacingleft.png",
"/assets/roles/roleimg_EM-04-22-crank.png",
"/assets/roles/roleimg_EM-04-23-poltergeist.png",
"/assets/roles/roleimg_EM-04-24-chandler.png",
"/assets/roles/roleimg_EM-05-00-bodyguard.png",
"/assets/roles/roleimg_EM-05-01-detective.png",
"/assets/roles/roleimg_EM-05-02-dreamer.png",
"/assets/roles/roleimg_EM-05-03-hunter.png",
"/assets/roles/roleimg_EM-05-04-templar.png",
"/assets/roles/roleimg_EM-05-05-baker.png",
"/assets/roles/roleimg_EM-05-06-blacksmith.png",
"/assets/roles/roleimg_EM-05-07-caroler.png",
"/assets/roles/roleimg_EM-05-08-killer.png",
"/assets/roles/roleimg_EM-05-09-anarchist.png",
"/assets/roles/roleimg_EM-05-10-sniper.png",
"/assets/roles/roleimg_EM-05-11-actress.png",
"/assets/roles/roleimg_EM-05-12-forger.png",
"/assets/roles/roleimg_EM-05-13-witch.png",
"/assets/roles/roleimg_EM-05-14-lookout.png",
"/assets/roles/roleimg_EM-05-15-toreador.png",
"/assets/roles/roleimg_EM-05-16-justice.png",
"/assets/roles/roleimg_EM-05-17-mechanic.png",
"/assets/roles/roleimg_EM-05-18-forager.png",
"/assets/roles/roleimg_EM-05-19-vicepresident.png",
"/assets/roles/roleimg_EM-05-20-friendlycop.png",
"/assets/roles/roleimg_EM-05-21-avenger.png",
"/assets/roles/roleimg_EM-05-22-resurrectionist.png",
"/assets/roles/roleimg_EM-05-23-vengeful-spirit.png",
"/assets/roles/roleimg_EM-05-24-martyr.png",
"/assets/roles/roleimg_EM-06-00-cop.png",
"/assets/roles/roleimg_EM-06-01-snoop.png",
"/assets/roles/roleimg_EM-06-02-wtfisthis.png",
"/assets/roles/roleimg_EM-06-03-towncrier.png",
"/assets/roles/roleimg_EM-06-04-shrink.png",
"/assets/roles/roleimg_EM-06-05-ghoul.png",
"/assets/roles/roleimg_EM-06-06-oracle.png",
"/assets/roles/roleimg_EM-06-07-siren.png",
"/assets/roles/roleimg_EM-06-08-clockmaker.png",
"/assets/roles/roleimg_EM-06-09-creepygirl.png",
"/assets/roles/roleimg_EM-06-10-illusionist.png",
"/assets/roles/roleimg_EM-06-11-tailor.png",
"/assets/roles/roleimg_EM-06-12-stalker.png",
"/assets/roles/roleimg_EM-06-13-ventriloquist.png",
"/assets/roles/roleimg_EM-06-14-ninja.png",
"/assets/roles/roleimg_EM-06-15-psychic.png",
"/assets/roles/roleimg_EM-06-16-cutler.png",
"/assets/roles/roleimg_EM-06-17-heartbreaker.png",
"/assets/roles/roleimg_EM-06-18-medusa.png",
"/assets/roles/roleimg_EM-06-19-whistleblower.png",
"/assets/roles/roleimg_EM-06-20-medium.png",
"/assets/roles/roleimg_EM-06-20-mourner.png",
"/assets/roles/roleimg_EM-06-21-queenbee.png",
"/assets/roles/roleimg_EM-06-22-mysterygraveyardrole.png",
"/assets/roles/roleimg_EM-06-23-clown.png",
"/assets/roles/roleimg_EM-06-24-waitress.png"]

export default class AvatarCarousel extends Component {
    constructor(props) {
        super(props);
        this.state = {
            selected: images[0].default
        };
        this.onSlide = this.onSlide.bind(this);
    }

    onSlide(index) {
        this.setState({ selected: images[index].default });
    }

    render() {
        return ( <
            div className = "Gallery" >
            <
            ImageGallery showPlayButton = { false }
            showFullscreenButton = { false }
            showThumbnails = { false }
            items = {
                images.map(function(image) {
                    return { original: image, originalHeight: 184 };
                })
            }
            onSlide = { this.onSlide }
            /> < /
            div >
        );
    }
};
